/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hhQtPXHQRHD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem } from "@/components/ui/carousel"
import { Card, CardContent } from "@/components/ui/card"

export function carousel() {
  return (
    (<div className="w-full max-w-6xl mx-auto py-12">
      <Carousel
        opts={{
          loop: true,
          autoplay: true,
          autoplaySpeed: 3000,
          slidesToShow: 3,
          slidesToScroll: 1,
          responsive: [
            { breakpoint: 1024, settings: { slidesToShow: 2, slidesToScroll: 1 } },
            { breakpoint: 640, settings: { slidesToShow: 1, slidesToScroll: 1 } },
          ],
        }}
        className="w-full">
        <CarouselContent>
          <CarouselItem>
            <div className="p-4">
              <Card className="shadow-md rounded-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  alt="Card Image"
                  width="300"
                  height="200"
                  className="w-full h-48 object-cover"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                <CardContent className="p-4">
                  <h3 className="text-lg font-semibold">Card Title</h3>
                  <p className="text-muted-foreground">This is a brief description of the card content.</p>
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="p-4">
              <Card className="shadow-md rounded-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  alt="Card Image"
                  width="300"
                  height="200"
                  className="w-full h-48 object-cover"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                <CardContent className="p-4">
                  <h3 className="text-lg font-semibold">Card Title</h3>
                  <p className="text-muted-foreground">This is a brief description of the card content.</p>
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="p-4">
              <Card className="shadow-md rounded-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  alt="Card Image"
                  width="300"
                  height="200"
                  className="w-full h-48 object-cover"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                <CardContent className="p-4">
                  <h3 className="text-lg font-semibold">Card Title</h3>
                  <p className="text-muted-foreground">This is a brief description of the card content.</p>
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="p-4">
              <Card className="shadow-md rounded-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  alt="Card Image"
                  width="300"
                  height="200"
                  className="w-full h-48 object-cover"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                <CardContent className="p-4">
                  <h3 className="text-lg font-semibold">Card Title</h3>
                  <p className="text-muted-foreground">This is a brief description of the card content.</p>
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
        </CarouselContent>
      </Carousel>
    </div>)
  );
}
